# Generated by Django 4.1.13 on 2024-08-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_user_input", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="role_name",
        ),
        migrations.AlterField(
            model_name="role",
            name="role_id",
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
