# Generated by Django 5.0.7 on 2024-09-08 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "role_id",
                    models.CharField(max_length=13, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "role",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "subject_id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("subject_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "subject",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=254, unique=True)),
                ("fte_percentage", models.FloatField(blank=True, null=True)),
                ("honorific", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING, to="core.role"
                    ),
                ),
            ],
            options={
                "db_table": "user_profile",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LecturerExpertise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "db_table": "lecturer_expertise",
                "managed": True,
                "unique_together": {("subject", "user")},
            },
        ),
    ]
