# Generated by Django 5.0.7 on 2024-10-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lecturerworkload"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecturerworkload",
            name="is_overloaded",
            field=models.BooleanField(default=False),
        ),
    ]
