# Generated by Django 5.0.7 on 2024-10-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_lecturerworkload_is_overloaded"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subjectinstance",
            name="enrollments",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
